<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Blog sur Final Fantasy</title>
    <script src="https://kit.fontawesome.com/ec539eaecf.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Open+Sans:ital@0;1&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="CSS/normalize.css">
    <link rel="stylesheet" href="CSS/style.css">

   <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>

</head>
<body>
    <header>
        <h1 class="titre">Blog Final Fantasy</h1>
        <a id="lienadmin" href="ressourceadministration.php"><i class="fas fa-users-cog"></i> Administration</a>
    </header>

    <main>
    <section id="toplink">
            <a class="retouracceuil" href="index.phtml"><i class="fas fa-home"></i>Retour à l'accueil</a>

            <a class="deconnexion" href="deco.php"><i class="fas fa-times-circle"></i>Me déconnecter</a>
        </section>
        
        <h1 class="acceuil"><i class="far fa-file-alt"></i>Articles</h1>

        <section id="detail-article-section">
                
                <h2 class="detail-article-titre"><?=$articles['titre']?></h2>

                <p class="pdetail"><?=$articles['article']?></p>
                
                <blockquote class="blockquoteindex">Rédigé par <?=$articles['pseudo']?> le <?=$articles['date_article']?>.</blockquote>

        </section>
        <?php if(empty($commentaire) == true){

        }else{?>
        <section class="affichagecomm">
            <h2 class="acceuil detail-article-titre">Commentaires</h2>
            <?php foreach ($commentaire as $comm){ ?>
                <article class="pseudocomm">
                    <p class="pseudo"><strong><i class="fas fa-comment"></i>Rédigé par <?=$comm['pseudo']?></strong></p>
                    <?php
                    session_start();

                    if(!isset($_SESSION['id_blogueur'])){
                        
                    }else{
                            echo '<a href=supcomm.php?idcomm='.$comm['id_comm'].'&amp;idart='.$comm['id_article'].'><i class="fas fa-times"></i></a>'; 
                    }
                    
                ?>
                </article>
                <p class="pseudocomm"><?=$comm['commentaire']?></p>
            
            <?php } 
                
                if(!isset($_SESSION['id_blogueur'])){
                    
                }else{
                    echo '<a class="deleteAllcomm" href="deleteAllcomm.php?idart='.$comm['id_article'].'">Supprimer tout les commentaires</a>'; 
                }
            
            ?>
       <?php } ?>
        
            
        </section>
        
        
        <section class="section-comm">
            <fieldset>
                <legend><i class="far fa-comment"></i>Nouveau commentaire</legend>
                <form id="addcomm" action="validcomm.php" method="POST">

                    <input type="hidden" name="idarticle" value="<?=$articles['id_article']?>">

                    <label for="pseudo">Pseudo : </label>
                    
                    <input class="textpseudo" type="text" name="pseudo" placeholder="Entrez votre pseudo">

                    <label for="commentaire">Commentaire : </label>
                    <textarea placeholder="Redigez votre commentaire ici." class="textcommentaire" name="commentaire" id="comm" cols="30" rows="10"></textarea>

                    <input class="bouton" type="submit" value="Envoyer">

                </form>
            </fieldset>
        </section>    

    </main>






<footer>
        
    </footer>

    </body>
</html>