<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Blog sur Final Fantasy</title>
    <script src="https://kit.fontawesome.com/ec539eaecf.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Open+Sans:ital@0;1&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="CSS/normalize.css">
    <link rel="stylesheet" href="CSS/style.css">

   <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>

</head>
<body>
    <header>
        
        <h1 class="titre">Blog Final Fantasy</h1>
        
    </header>

    <main>
    <section id="toplink">
        <a class="retouracceuil" href="index.phtml"><i class="fas fa-home"></i>Retour à l'accueil</a>
</section>

        <section class="section-comm-inscription">
        <fieldset >
            <legend><h2>Inscription</h2></legend>
            <form class="inscription" method="POST" action="validinscription.php">
            
                

                <label class="labelinscription" for="pseudo">Votre pseudo : </label>
                <input type="text" name="pseudo" placeholder="Choisissez un pseudo">

                <label class="labelinscription" for="email">Votre email : </label>
                <input class="Sizeemailinput" type="email" name="email" placeholder="Entrez une adresse email valide">

                <label class="labelinscription" for="password">Mot de passe : </label>
                <input type="password" name="password" placeholder="Entrez un mot de passe">

                <input class="bouton" type="submit" id="inscriptionbutton" value="Envoyer">
            </form>
        </fieldset>
</section>

        
    </main>
    <footer>
        
    </footer>

    </body>
</html>