<?php

            session_start();
            
            include 'connexionBDD.php';

            $query = $pdo->prepare
            (
                'SELECT * FROM blogueur where id_blogueur = ?'
            );
            $query->execute([$_SESSION['id_blogueur']]);
            $user = $query->fetch();

            ?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Blog sur Final Fantasy</title>
    <script src="https://kit.fontawesome.com/ec539eaecf.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Open+Sans:ital@0;1&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="CSS/normalize.css">
    <link rel="stylesheet" href="CSS/style.css">

   <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>

</head>
<body>
    <header>
       
        <h1 class="titre">Blog Final Fantasy</h1>
        
 <a id="lienadmin" href="ressourceadministration.php"><i class="fas fa-users-cog"></i> Administration</a>
    </header>

    <main>
       
    <section id="toplink">
            <a class="retouracceuil" href="index.phtml"><i class="fas fa-home"></i>Retour à l'accueil</a>

            <a class="deconnexion" href="deco.php"><i class="fas fa-times-circle"></i>Me déconnecter</a>
        </section>

        <fieldset id="fieldsetnewarticle">
            <legend><h1>Nouvel article</h1></legend>
            <form id="addcomm" method="POST" action="addarticle.php">
            
                    <label for="titre">Titre :</label>
                    <input id="newtitlenew" type="text" name="titre" placeholder="Mettez votre titre ici.">

                    <label for="article">Contenu de l'article :</label>
                    <textarea placeholder="Redigez votre article ici." id="newarticle" name="article" rows="10"></textarea>

                    <label for="categorie">Catégorie :</label>
                    <select name="categorie" id="categorie">
                        <option value="jeux-video">Jeux-vidéos</option>
                        <option value="actualite">Actualité</option>
                        <option value="personnage">Évènement</option>
                    </select>

                    <input type="hidden" name="pseudo" value="<?=$user['pseudo']?>">
                    <input type="hidden" name="idblogueur" value="<?=$user['id_blogueur']?>">
                
                    <input class="boutonnouvelarticle" type="submit" name="envoyer" value="Envoyer">
            </form> 
        </fieldset>



    </main>

    <footer>
        
    </footer>

    </body>
</html>