<!DOCTYPE HTML>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <script src="https://kit.fontawesome.com/ec539eaecf.js" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link rel="stylesheet" href="CSS/style.css">
        <title>Encyclopedie Dofus</title>
    </head>

    <body>
        <header>
            <a href="index.phtml"><img src="Images/Logo Dofus.png" class="logo" alt="Logo Dofus"></a>
            <nav id="navbar" class="navbar">
                <a href="chapeaux.phtml"><img src="Images/chapeau.png" class="icone_nav">Chapeaux</a>
                <a href="Amulettes.phtml"><img src="Images/amulette.png" class="icone_nav">Amulettes</a>
                <a href="Ceintures.phtml"><img src="Images/ceinture.png" class="icone_nav">Ceintures</a>
                <a href="Anneaux.phtml"><img src="Images/anneau.png" class="icone_nav">Anneaux</a>
                <a href="Bottes.phtml"><img src="Images/botte.png" class="icone_nav">Bottes</a>
                <a href="Capes.phtml"><img src="Images/cape.png" class="icone_nav">Capes</a>
                <a href="Pets.phtml"><img src="Images/pets.png" class="incone_nav">Pets</a>
            </nav>

        </header>
        <?php 
                session_start();
                if(isset($_SESSION['id_user'])){ ?>
                    <section>
                        <p class="user">Bonjour <?= $_SESSION['pseudo'] ?></p>
                        <a href="equipement.phtml">Mon équipements</a>
                        <a href="sedeconnecter.php">Se déconnecter</a>
                    </section>

              <?php } else { 
                  
                  ?>
                  
                <section>

                <form action="login.php" method="POST" name="login" id="login">

                     <label for="email">Email : </label>
                    <input type="email" name="email" require>
                
                    <label for="password">Mot de passe : </label>
                    <input type="password" name="password">
                
                <button type="submit" id="login_button">Se connecter</button>

                </form>

               <button id="button_inscription">Pas encore inscrit ?</button>

              

                <form action="inscription.php" method="POST" id="inscription" class="hide">
                    <fieldset>

                    <legend>Inscription</legend>
                    
                    
                        <label for="email">Entrez votre adresse email : </label>
                    <input type="email" name="email" id="email" require>
                    
                    
                    
                        <label for="password">Entrez votre mot de passe : </label>
                        <input type="password" name="password" require>
                    
                        <label for="pseudo">Choisissez votre pseudonyme : </label>
                        <input type="text" name="pseudo" require>
                    

                    <input type="submit" value="S'inscrire" id="Subscribe_button">
                </form>
            </fieldset>
               

                
            </section>

            <?php

if($_GET['err'] == 1 ){?>
<p class="error">Vous êtes déjà inscrit sur le site.</p>
<?php } else if($_GET['success'] == 1) {?>
        <p class="success">Inscription réussie</p>

        <?php } ?>

            <?php 

if($_GET['err'] == 2){?>
    <p class="error">Vos informations sont incorrect.</p>
<?php } ?>
                  
                 
            
             <?php } ?>
        <main>
            <h1>Votre équipement</h1>
            <table id="equipement">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Type</th>
                    <th>Description</th>
                    <th>Niveau d'objet</th>
                    <th>Statistiques</th>
                </tr>
                
            </thead>
            <tbody>
 <?php


include 'utilities.php';

for($i = 0 ; $i < count($_SESSION['equipement']['id']); $i++){

    if($_SESSION['equipement']['type'][$i] == "Familier"){
        $datas = file_get_contents('https://fr.dofus.dofapi.fr/pets/'.$_SESSION['equipement']['id'][$i]);// Fais appel à l'API sur une URL
        $objet = json_decode($datas, TRUE);
?>
        
            <tr>
                <td class="NomObjet"><a href="petsDetails.phtml?id=<?= $objet['_id'] ?>"><?= $objet['name'] ?></a></td>
                <td class="type"><?= $objet['type'] ?></td>
                <td class="description"><?= $objet['description'] ?></td>
                <td class="niveau"><?= $objet['level'] ?></td>
                <td class="Equipement_Statistique"><?php Statistiques($objet); ?></td>
                <td><a href="supprimerunobjet.php?id=<?= $objet['_id'] ?>">Supprimer l'objet</a></td>
            </tr>
<?php } 
    else{
        $datas = file_get_contents('https://fr.dofus.dofapi.fr/equipments/'.$_SESSION['equipement']['id'][$i]);// Fais appel à l'API sur une URL
        $objet = json_decode($datas, TRUE); 
?>



                <tr>
                    <td class="NomObjet"><a href="objet.phtml?id=<?= $objet['_id'] ?>"><?= $objet['name'] ?></a></td>
                    <td class="type"><?= $objet['type'] ?></td>
                    <td class="description"><?= $objet['description'] ?></td>
                    <td class="niveau"><?= $objet['level'] ?></td>
                    <td class="Equipement_Statistique"><?php Statistiques($objet); ?></td>
                    <td><a href="supprimerunobjet.php?id=<?= $objet['_id'] ?>">Supprimer l'objet</a></td>
                </tr>

<?php  } } ?>

                <tr>
                    <td class="Total_Statistique" colspan="3">Calcul des statistiques</td>
                    <td colspan="2"><?= calculStatistique() ?></td>
                </tr>
</tbody>          
</table>
        </main>

        <footer>
            <p>Dofapi</p>
        </footer>
        <script src="javascript/jquerycss.js"></script>
    </body>
    </html>